### ISSUE TITLE
TODO May 7

### ISSUE THREAD

**Issue by tengjiang** [daFPGASwitch/daFPGASwitch#1]
Ingress:
- [x] VMU (VOQ management unit, no algo) with testbench - Teng
- [ ] CMU (control memory unit, the memory allocation algo) with testbench - Irfan, Ilgar (questionably done?)
- [ ] Packet gen and device driver. A buffer to store the packet  (both about design and implementation) - Lauren, Ilgar 
 * Generate patterns in software in whatever language
 * Send (by sending, I meant a device driver) the pattern/the real packet (up to you) to store it in some packet buffer (if software sends the packet, you need a buffer. If hardware generates packets, then just send it to the ingress (still need the pattern buffer) (✅))
- [x] Mac to port and Mac to port device driver (talks to software) - Lauren, Ilgar
 * We can hard code it in hardware first
 * Then use software to control it
- [ ] Input module (driven by state machine) with test bench; **Add start time stamp to the packet (Advanced)** - Together
- [ ] Output module state (driven by state machine) with test bench; **Add end time stamp to the packet (Advanced)** - Together - Teng

Egress: - Teng and Fathima
- [x] Receiver: talks to crossbar, store it in the local ring buffer
- [x] Device driver that sends every packet (or the metadata, just packet id, time stamps...) out (after all being transferred) to software (after we're all done), for the software to do analysis (2 parts: correctness (have to), performance (good to have, advanced)).

Crossbar (easy): - Teng and someone
- [x] Crossbar with testbench

Advanced:
* I have at least 2 sched_policy to test out. So we can compare the performance of the algo.

Report:
- [ ] Sched policy definition - Teng
- [ ] Memory management unit - Irfan
- [ ] Packet definition - Lauren Ilgar

Move to hardware:
- [ ] Makefile Ilgar and Lauren
